config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "welcome/index"
  root "welcome#index"
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
    validates :first_name, :last_name, :email, presence: true
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/students_controller.rb
class StudentsController < ApplicationController
  
    before_action :set_student, only: %i[show edit update destroy]
    def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  # Creating new student
  def create
    @student = Student.new(
      # first_name: params[:student] [:first_name],
      # last_name: params[:student] [:last_name],
      # email: params[:student] [:email]
      student_params
    )

    if @student.save()
      redirect_to students_path, notice: "Student created successfully!"
    else
      render :new
    end
  end

  # View new student
  def show
    set_student
    if @student.nil?
      flash[:alert] = "Student not found."
      redirect_to students_path # Redirect to the index page or another appropriate page
    end
  end

  def edit 
    set_student
  end

  def update 
    set_student
   if  @student.update(student_params)
    redirect_to student_path(@student), notice: "Student updated successfully!"
   else
    render :edit
   end
  end
  def destroy
    set_student
    if @student
      @student.destroy
      redirect_to students_path, notice: "Student deleted successfully!"
    else
      flash[:alert] = "Student not found."
      redirect_to students_path 
    end
  end


  #   Requirement params
  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :email)
  end
  def set_student
    @student = Student.find_by(id: params[:id])
  end
end

app/controllers/concerns/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
    end
end    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentDatabase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>
<% if @student.errors.any? %>
<% @student.errors.full_messages.each do |message| %>
<p><%= message %></p>
<%end%>
<%end%>
<div>
    <%= form.label :first_name %> <br>
    <%= form.text_field :first_name %>
</div>
<div>
    <%= form.label :last_name %> <br>
    <%= form.text_field :last_name %>
</div>
<div> 
    <%= form.label :email %> <br>
    <%= form.text_field :email %>
</div>
<div>
    <%= form.submit %>
</div>

<%end%>

app/views/students/edit.html.erb
<h1>
    Edit Students
</h1>
<%= render "form", student: @student %>

app/views/students/index.html.erb
<p><%= notice %></p>
<h1>Listing all Students</h1>
<%= link_to "New Student", new_student_path %>

    <table>
        <thead>
            <tr>
                <th>First name </th>
                <th>Last name </th>
                <th>Email </th>
                <th colspan="3">Actions</th>

            </tr>
        </thead>
        <tbody>
            <% @students.each do |student| %>
            <tr>
                <td><%= student.first_name %></td>
                <td><%= student.last_name %></td>
                <td><%= student.email %></td>
                <td><%= link_to "View Details", student %></td>
                <td><%= link_to "Update", edit_student_path(student) %></td>
                <td><%= link_to "Delete", student, method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}%></td>
            </tr>
            <%end%>
        </tbody>

    </table>

app/views/students/new.html.erb
<h1>
    New Students
</h1>

<%= render "form", student: @student %>

app/views/students/show.html.erb
<p><%= notice %></p>
<h1>Students details</h1>

<p><strong>First Name: </strong><%= @student.first_name %></p>
<p><strong>Last Name: </strong><%= @student.last_name %></p>
<p><strong>Email: </strong><%= @student.email %></p>

<%= link_to "All Students", students_path %> |
<%= link_to "Update", edit_student_path(@student) %>

app/views/welcome/index.html.erb
<h1>
Welcome to my ruby Application
</h1>